### ISSUE TITLE
Remove loading WX automatically when using scimath.units.api

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/scimath#13]
Certain scimath objects define a TraitsUI editor which depends on wx. Unfortunately the imports are not hidden in the method that uses it and as a consequence, when someone imports anything from scimath.units.api, that imports wx and launches a GUI event loop. It slows things down.

**Comment by rahulporuri** [comment]
i'm not entirely sure when this got fixed but this isn't a problem at the moment. i'm able to import `scimath.units.api` without `wx` in the environment.

**Comment by rahulporuri** [comment]
update - it looks like these got fixed in the commit https://github.com/enthought/scimath/commit/1c4b63b663edc58df4a2b22609a9132f26112eab#diff-be8bee3902170f7fc30ef78962da2d0c35fd547ddaa1c435dd6426270245a1f0. closing.
