### ISSUE TITLE
Update documentation of scimath to include test environment setup

### ISSUE THREAD

**Issue by homosapien-lcy** [enthought/scimath#165]
The scimath readme has been outdated, it's not easy for people who is new on the scimath development project to setup the environment for development. We need an update to add information of test environment setup.

**Comment by homosapien-lcy** [comment]
readme update is done in PR #164 https://github.com/enthought/scimath/pull/164/files

**Comment by mdickinson** [comment]
@homosapien-lcy I see you closed this issue. Which PR was this done in?

**Comment by mdickinson** [comment]
I'm not seeing any changes to the `README.rst` on the main branch. I'll re-open.

**Comment by homosapien-lcy** [comment]
I think I wan't intended to do that since the issue hasn't been merged... It is issue #167
