### ISSUE TITLE
When we test pypi with python 3.6 and ubuntu 22.04, a architecture not found error will happen

### ISSUE THREAD

**Issue by homosapien-lcy** [enthought/scimath#170]
Problem description:
If python 3.6 is added to the pypi test, it will generate a "The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04." error.

Reproduction steps:
Add 3.6 to .github/workflows/test-with-pypi.yml. See code change in this PR.

Expected behavior:
Pas the github workflows test.

OS: Ubuntu 22.04

Python version: 3.6

See PR #169 for details

**Comment by mdickinson** [comment]
I think this is fine - we should no longer be supporting Python 3.6. It's way beyond end-of-life, and Python 3.6 support has already been dropped for some dependent packages.

What was the motivation for adding 3.6 to the `test-with-pypi` workflow?

**Comment by mdickinson** [comment]
I'll close here - I don't think there's anything we need to fix.
