### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Elfangor93** [enthought/scimath#178]
I wanted to install scimath on a windows 10 computer featuring python 3.12.0.
The installation ends telling that git_revision can not be imported. Any idea how to solve that?
![image](https://github.com/enthought/scimath/assets/39154009/cdfd77e0-e730-4d1b-8fa7-4c4e4eed081a)

**Comment by Elfangor93** [comment]
I just tried with Python 3.11.6 and it is working here. So seems like there is a compatibility issue in the setup script...

**Comment by mdickinson** [comment]
Thanks for the report! It looks as though there's an issue in our setup.py script where we try to use `import` on a file that isn't discoverable via `sys.path`, [here](https://github.com/enthought/scimath/blob/e42a1d7342096b0e39132c1466afaef37d9dd84f/setup.py#L86-L87): it's been there for a good while, but my guess is that changes in some recent version of pip have caused previously-working code to fail. It should be an easy fix, though it would be better to overhaul/modernize the build configuration entirely.

https://github.com/pypa/pip/pull/7955 may be relevant.

FWIW, the problem isn't specific to Python 3.12 - it's just that we don't have any wheels on PyPI for Python 3.12, so your system then tries to build from the source distribution. If you force installation from sdist via `pip install --no-binary scimath scimath`, then it fails in exactly the same way on Python 3.11.
