### ISSUE TITLE
wrong unit conversion

### ISSUE THREAD

**Issue by CMartelLML** [enthought/scimath#39]
Hello,

I just installed scimath with pip, and I'm testing the conversion between units, as I think it's a really helpful feature.
But I think there is an issue : 

```javascript
import scimath.units as sci
In [27]: sci.convert(6.28,sci.angle.radians,sci.angle.deg)
Out[27]: 3598.17495342157
```

It should return 359.8 : I think there is a factor 10 mistake in the implementation of one of the unit. I tested the other way around 'converting deg to radians) and it is also wrong by a 10 factor.

**Comment by CMartelLML** [comment]
I just re-tested and the result is OK.
Apparently I changed the `value` of rad by 10, leading to this. Sorry about this false alarm.

**Comment by mdickinson** [comment]
No problem.  Thanks for the report.
