### ISSUE TITLE
Units not __future__.division proof

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/scimath#55]
The following snippet of code returns the wrong result with `__future__.division` import (Python 2.7):
```
#from __future__ import division
from scimath.units.api import UnitScalar
x = UnitScalar(1.2, units="kg/m**3")
print repr(x/100.)
```

**Comment by mdickinson** [comment]
To be clear, I assume that it's the units of the result that you're referring to? That is, I get:
```
UnitScalar(0.012, units='1.0*m**-3*kg+0.0')
```
with the `__future__` import disabled, and
```
UnitScalar(0.012, units='None')
```
with the `__future__` import enabled. I assume you're seeing the same?

**Comment by mdickinson** [comment]
The fix seems to be as simple as adding the line `__truediv__ = __div__` to the `UnitArray` class definition. But the source should be examined carefully to determine where else it might be appropriate to add `__truediv__ = __div__`, and possibly also `__rtruediv__ = __rdiv__`.  (And of course, any fix should include appropriate tests.)

**Comment by jonathanrocher** [comment]
Yes @mdickinson that is correct. Thanks for clarifying and finding the fix! I will try to get to it...

**Comment by mdickinson** [comment]
Looks like this is only an issue on Python 2, which we've long-since ceased to care about.

On Python 3.8, I get this:

```python
>>> from scimath.units.api import UnitScalar
>>> x = UnitScalar(1.2, units="kg/m**3")
>>> x/100.
UnitScalar(0.012, units='1.0*m**-3*kg')
```

Closing here.
