### ISSUE TITLE
Accidental (?) implicit dependency on TraitsUI

### ISSUE THREAD

**Issue by andrewcollette** [enthought/scimath#56]
The package doesn't advertise TraitsUI as a dependency, but attempting to run e.g. `from scimath.units.api import UnitScalar` crashes with an ImportError if it's not installed.  It's highly desirable that it be usable with Traits only, as we will be deploying code on headless systems.

The culprit appears to be this line (although there may be others): https://github.com/enthought/scimath/blob/7ba4cc62edfe4e3aac0b049458776a7f84679820/scimath/units/family_name_trait.py#L94

This is an issue for our consulting project, so I could spend some time on it if folks can point me in the right direction.  See also #8.

**Comment by rkern** [comment]
We don't generally avoid all `traitsui` imports in such cases. This is why `traitsui` has the `null` backend and is generally careful to avoid actual toolkit imports until someone actually calls `.edit_traits()`.

**Comment by andrewcollette** [comment]
Thanks @rkern! I will admit to being a little confused here... we recently had a discussion on that consulting project about the value of structuring code to avoid TraitsUI imports for non-GUI things.  It looks like, since the model objects use UnitScalar, TraitsUI is unavoidable?

In any case, it looks like the comment in the above file is wrong, as it suggests the import is delayed specifically to avoid loading UI code (which may have been the motivation, but it's not what happens).

**Comment by rkern** [comment]
I failed to give the fully-nuanced general rules for simplicity's sake (the specific actions you had proposed were perfectly reasonable, so I didn't want to sidetrack). :-) My apologies.

Indeed the comment is bogus. This trait ought to be rewritten as a `TraitType` with the editor import placed inside of a `get_editor()` method. This trait predates `TraitType`, I think.
