### ISSUE TITLE
Appveyor CI

### ISSUE THREAD

**Issue by rahulporuri** [enthought/scimath#81]
While CI was setup in #71 , we currently only have travis running on pull requests and not appveyor. Appveyor builds aren't being triggered by pull requests, which needs to be sorted out.

**Comment by mdickinson** [comment]
@rahulporuri The scimath project hadn't been added to Appveyor (this can be done through the Appveyor web UI, and I'm not sure whether everyone can do it). In any case, I've now done that.

**Comment by mdickinson** [comment]
Hmm. But it appears as though Appveyor hasn't added a webhook to this repo. Not sure what's going on there.

**Comment by mdickinson** [comment]
My guess is that Appveyor was previously configured, but the webhook was deleted at some point (no idea why). I've re-added the webhook manually.

Appveyor seems to be working now on #82, so I'm closing this as fixed.

**Comment by rahulporuri** [comment]
Thanks for that @mdickinson !
