### ISSUE TITLE
Error on install - requires Microsoft Visual C++ 14.0 or greater 

### ISSUE THREAD

**Issue by jgrooviest** [enthought/scimath#98]
Is scimath actually dependent on Microsoft Visual C++? That seems to be where the install (`pip install scimath`) is getting hung up on when it attempts to build the wheel: 

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for scimath

```

**Comment by mdickinson** [comment]
scimath does include a C++ extension, and we don't currently build or upload wheels, so yes, doing a `pip install scimath` does currently require a C++ compiler.

**Comment by mdickinson** [comment]
Sorry, I meant to include the relevant code link in the last message. See https://github.com/enthought/scimath/blob/985cd629421016fe1f1801eb7acb32475ac6e44f/scimath/interpolate/setup.py#L9-L13

**Comment by jgrooviest** [comment]
Ah, okay, might look into another package for units then. Thanks for being so responsive!

**Comment by mdickinson** [comment]
A quick follow-up: we *will* likely get around to building wheels for scimath at some point, but it's not high on the priority list. (It's not a need for our internal uses of scimath at Enthought, since we have our own build system.)
